"""A collection of functions to visualize the explanations generated for a video sample."""

import logging
import torch
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from captum.attr import LayerAttribution


def plot_explanations(
    clip:np.ndarray, 
    attr_gradcam:torch.Tensor, 
    attr_kernelshap:torch.Tensor, 
    sample_id:int, 
    model_name:str, 
    interpolate:bool,
    add_boundaries:bool,
    boundaries_gradcam:list, 
    segments_kernelshap:list,
    save_dir:str,
):
    """Plot the original video frames, the Grad-CAM saliency map, and the KernelSHAP saliency map."""
    n_frames = clip.shape[0]

    if interpolate:
        visualization_type = "interpolated"
    else:
        visualization_type = "raw"

    fig = plt.figure(figsize=(3*n_frames, 8))
    gs = gridspec.GridSpec(3, n_frames + 1, width_ratios=[1]*n_frames + [0.05], wspace=0.02, hspace=0.05)

    # Main title
    fig.suptitle(f"{visualization_type} explanations for test sample '{sample_id}' and {model_name} model", fontsize=16, y=0.98)

    # Row titles
    fig.text(0.10, 0.76, "Original", fontsize=12, rotation=90, va="center")
    fig.text(0.10, 0.50, "Grad-CAM", fontsize=12, rotation=90, va="center")
    fig.text(0.10, 0.23, "KernelSHAP", fontsize=12, rotation=90, va="center")

    # Row 1: original images
    for col in range(n_frames):
        ax = fig.add_subplot(gs[0, col])
        ax.imshow(clip[col])
        ax.set_title(f"Frame {col+1}", fontsize=12)
        ax.axis("off")

    # Row 2: Grad-CAM
    gc_min, gc_max = np.min(attr_gradcam), np.max(attr_gradcam)
    gc_abs_max = np.max([abs(gc_min), abs(gc_max)])   # to ensure red for all positive attributions and blue for all negative attributions
    for col in range(n_frames):
        ax = fig.add_subplot(gs[1, col])
        heat = attr_gradcam[col].squeeze()
        im_grad = ax.imshow(heat, cmap="coolwarm", vmin=-gc_abs_max, vmax=gc_abs_max)
        if add_boundaries:
            ax.contour(boundaries_gradcam, levels=[0.5], colors='yellow', linewidths=0.7)
        ax.axis("off")

    # Row 3: KernelSHAP
    ks_min, ks_max = np.min(attr_kernelshap), np.max(attr_kernelshap)
    ks_abs_max = np.max([abs(ks_min), abs(ks_max)])
    for col in range(n_frames):
        ax = fig.add_subplot(gs[2, col])
        heat = attr_kernelshap[col].squeeze()
        im_shap = ax.imshow(heat, cmap="coolwarm", vmin=-ks_abs_max, vmax=ks_abs_max)
        if add_boundaries:
            ax.contour(segments_kernelshap[col], levels=np.unique(segments_kernelshap[col]), colors='yellow', linewidths=0.7)
        ax.axis("off")

    # Colorbar for Grad-CAM
    cax1 = fig.add_subplot(gs[1, -1])
    cbar1 = fig.colorbar(im_grad, cax=cax1)
    cbar1.set_label("Contribution", fontsize=10)

    # Colorbar for KernelSHAP
    cax2 = fig.add_subplot(gs[2, -1])
    cbar2 = fig.colorbar(im_shap, cax=cax2)
    cbar2.set_label("Contribution", fontsize=10)

    plt.savefig(f"{save_dir}/{visualization_type}_explanations.png", dpi=300, bbox_inches="tight")
    #plt.show()
    plt.close()


def visualize_video_saliency(
    video_tensor:torch.Tensor,
    raw_attr_gradcam:torch.Tensor,
    raw_attr_kernelshap:torch.Tensor,
    sample_id:int,
    model_name:str,
    segments_per_frame:list,
    feature_division:str,
    n_segments:list[int],
    save_dir:str,
    add_boundaries:bool=False,
    interpolate:bool=False,
):
    """ Visualize the saliency maps for a given video sample.

    Args:
        video_tensor: Original video frames in shape [B, C, T, H, W], typically [1, 3, 6, 224, 224].
        raw_attr_gradcam: The raw saliency map generated by GradCAM in shape [T, C, H, W].
        raw_attr_kernelshap: The raw saliency map generated by KernelSHAP in shape [B, n_features].
        sample_id: The input sample for which the explanations are generated.
        model_name: The model for which the explanations are generated.
        segments_per_frame: The segmentation of pixels into input features used for KernelSHAP in shape (T, H, W).
        feature_division: The method used to define input features for KernelSHAP.
        n_segments: The number of segments per img axis used for grid-based input feature division.
        save_dir: The directory where the saliency maps and plot will be saved.
        add_boundaries: Whether to show the boundaries of the input features.
        interpolate: Whether to interpolate raw saliency scores for visualization convenience. 
    """
    # ------------------------
    # ORIGINAL INPUT
    # ------------------------
    # Remove batch dimension if present
    if video_tensor.dim() == 5: 
        video_tensor = video_tensor[0] 
    # Move everything to CPU for visualization
    video_tensor = video_tensor.detach().cpu()
    raw_attr_gradcam = raw_attr_gradcam.detach().cpu()
    raw_attr_kernelshap = raw_attr_kernelshap.detach().cpu()
    # Check for unexpected dimensions
    if video_tensor.dim() != 4:
        raise ValueError(f"Expected video_tensor with shape [C, T, H, W], but got {video_tensor.shape}")
    # Denormalize 
    imagenet_mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1, 1) 
    imagenet_std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1, 1)
    video_tensor = video_tensor * imagenet_std + imagenet_mean 
    # Convert from [C, T, H, W] → [T, H, W, C]
    frames = video_tensor.permute(1, 2, 3, 0).cpu().numpy() 
    num_frames, height, width, channels = frames.shape
    logging.info(f"Video tensor shape: {frames.shape}")

    # ------------------------
    # GRAD-CAM
    # ------------------------
    _, _, saliency_map_height, saliency_map_width = raw_attr_gradcam.shape
    patch_height = int(height / saliency_map_height)
    patch_width = int(width / saliency_map_width)
    # Upsample the saliency map to match the input video shape
    if interpolate:
        attr_gradcam = LayerAttribution.interpolate(layer_attribution=raw_attr_gradcam, interpolate_dims=(height, width), interpolate_mode="bilinear")
    else:
        attr_gradcam = raw_attr_gradcam.repeat_interleave(patch_height, dim=2).repeat_interleave(patch_width, dim=3)
    # Convert from [T, C, H, W] -> [T, H, W, C]
    attr_gradcam = attr_gradcam.permute(0, 2, 3, 1).detach().cpu().numpy()
    logging.info(f"Upsampled GradCAM attribution shape: {attr_gradcam.shape}")
    np.save(f"{save_dir}/attr_gradcam.npy", attr_gradcam)
    # Save superpixel boundaries
    if add_boundaries:
        boundaries_gradcam = np.zeros((height, width), dtype=bool)
        # Add horizontal lines
        for y in range(0, height, patch_height):
            boundaries_gradcam[y:y+1, :] = True
        # Add vertical lines
        for x in range(0, width, patch_width):
            boundaries_gradcam[:, x:x+1] = True
    else:
        boundaries_gradcam = None

    # ------------------------
    # KernelSHAP
    # ------------------------
    if interpolate:
        if feature_division == "grid":
            # Get low resolution saliency map
            attr_kernelshap = raw_attr_kernelshap.squeeze(0).reshape(num_frames, n_segments[0], n_segments[1])
            # Add channel dimension
            attr_kernelshap = attr_kernelshap.unsqueeze(1)  
            # Upsample the saliency map to match input video shape
            attr_kernelshap = LayerAttribution.interpolate(layer_attribution=attr_kernelshap, interpolate_dims=(height, width), interpolate_mode="bilinear")
            # Convert from [T, C, H, W] -> [T, H, W, C]
            attr_kernelshap = attr_kernelshap.permute(0, 2, 3, 1).detach().cpu().numpy()
        else:
            raise NotImplementedError("Interpolation for SLIC_clip and SLIC_frame is not implemented yet!")
    else:
        raw_attr_kernelshap = raw_attr_kernelshap.detach().cpu().numpy()
        raw_attr_kernelshap = raw_attr_kernelshap.squeeze(0)  # (n_features,)
        segments = segments_per_frame
        attr_kernelshap = raw_attr_kernelshap[segments]
        # Add channel dimension
        attr_kernelshap = np.expand_dims(attr_kernelshap, axis=3)
    logging.info(f"Upsampled KernelSHAP attribution shape: {attr_kernelshap.shape}")
    np.save(f"{save_dir}/attr_kernelshap.npy", attr_kernelshap)

    # Show explanations for both methods as an overlayed heatmap on the video frames
    plot_explanations(
        frames, 
        attr_gradcam, 
        attr_kernelshap, 
        sample_id, 
        model_name, 
        interpolate, 
        add_boundaries,
        boundaries_gradcam,
        segments_per_frame,
        save_dir,
    )